import css from "../styles/TableExplanation.module.css";

const TableExplanation = () => {
  return (
    <div className={css.explanationBox}>
      <h4 className={css.title}>How to Read the Transaction Risk Table</h4>

      <p className={css.text}>
        The table above provides a detailed, transaction-level view of the system’s
        anomaly analysis. Each row represents a single transaction processed through
        the detection pipeline.
      </p>

      <ul className={css.list}>
        <li>
          <span>Transaction ID & User ID</span> uniquely identify each transaction and
          its associated user.
        </li>

        <li>
          <span>Amount</span> indicates the monetary value of the transaction in INR.
        </li>

        <li>
          <span>Location</span> represents the geographical origin of the transaction.
        </li>

        <li>
          <span>Risk Assessment</span> summarizes the system’s evaluation:
          <ul className={css.subList}>
            <li>
              <b>Normal</b> — no unusual patterns were detected for this transaction.
            </li>
            <li>
              <b>Anomaly</b> — one or more statistical or behavioral irregularities were
              identified.
            </li>
          </ul>
        </li>
      </ul>

      <p className={css.footer}>
        For anomalous transactions, the explanation is generated by an AI model that
        rewrites detected conditions into clear, human-readable insights while
        strictly avoiding assumptions or intent-based conclusions.
      </p>
    </div>
  );
};

export default TableExplanation;
